baseURL = 'https://blueridgeboost.com/pythonbook'
languageCode = 'en-us'
title = 'How to Think Like a Computer Scientist: Learning with Python 3 (Blue Ridge Boost Edition)'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

disableLiveReload = true
enableRobotsTXT = true
cleanDestinationDir = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Author of the site, will be used in meta information
  author = "Nora Evans and David Evans"
  # Description of the site, will be used in meta information
  description = "Learn Python at Blue Ridge Boost!"
  title = "How to Think Like a Computer Scientist: Learning with Python 3 (Blue Ridge Boost Edition)"

  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = false
  landingPageURL = "/pythonbook"
  landingPageName = "<i class='fas fa-home'></i> Home"

  brand_img = "images/brand/blue-ridge-highlands.webp"
  brand = "Blue Ridge Boost"

  # Change the title separator. Default to "::".
  titleSeparator = "-"

  editURL = ""

  showVisitedLinks = false
  
  # Disable search function. It will hide search bar
  disableSearch = false
  
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
 
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = false
  # Specifies the remote location of the mermaid js
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = []
  


[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"
      
    [[module.mounts]]
      source = "node_modules/lazysizes/"
      target = "assets/lazysizes/"

    [[module.mounts]]
        source = "assets"
        target = "assets"